### ISSUE TITLE
Statefile gets deleted repeatedly

### ISSUE THREAD

**Issue by Asmod4n** [onelogin/aead#6]
https://github.com/onelogin/aead/blob/master/lib/aead/nonce.rb#L38 stores the statefile in a directory which gets deleted repeatedly, according to https://tools.ietf.org/html/rfc5116#section-3.1 the file must be kept in the event of failure.

But afaik /var/tmp gets wiped in boot, or is even stored in a tmpfs.

**Comment by jtdowney** [comment]
According to the [Linux Filesystem Hierarchy Standard (LHS)](http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard):

> /var/tmp - Temporary files to be preserved between reboots.

That doesn't mean every Linux distro follows the standard, not to mention every other operating system ruby can run on. At the very least it would probably make sense to allow the gem consumer to set where they want the file (without monkey patching).
